### ISSUE TITLE
can't open file 'Demuxalot.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by changostraw** [drneavin/Demultiplexing_Doublet_Detecting_Docs#28]
Hi @drneavin,
I just downloaded the most recent Demuxafy.sif in order to try some of the new tools you have added and I can't seem to run Demuxalot. I get this error:

/opt/conda/envs/py37/bin/python: can't open file 'Demuxalot.py': [Errno 2] No such file or directory. 
I guess it is looking for it in the conda environment and not in the singularity image? 

I have identified all the paths with --bind so I don't think that is the issue. On our clusters we are using apptainer/1.1.8 instead of singularity if that is important. 

Here is the singularity image version I have: 
Author: = Drew Neavin
Image_version: = 2.1.0
org.label-schema.build-arch: amd64
org.label-schema.build-date: Friday_3_November_2023_1:10:54_UTC
org.label-schema.schema-version: 1.0
org.label-schema.usage.singularity.deffile.bootstrap: docker
org.label-schema.usage.singularity.deffile.from: drneavin/demuxafy:v2.0.1
org.label-schema.usage.singularity.version: 3.11.3-dirty

Thanks!

**Comment by drneavin** [comment]
Hi @changostraw , thanks for raising this issue. There is a typo in the Demuxalot documentation. Instead of 

`singularity exec Demuxafy.sif python Demuxalot.py ...` 

it should be 

`singularity exec Demuxafy.sif Demuxalot.py ...` 

So remove the `python`rom the command. I have it on my to-do list to update this in the docs. I'll keep this issue open until I've updated that in the docs.

**Comment by drneavin** [comment]
Fixed in [v3.0.0](https://github.com/drneavin/Demultiplexing_Doublet_Detecting_Docs/releases/tag/v3.0.0)
