### ISSUE TITLE
Dropulation - System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down

### ISSUE THREAD

**Issue by Thapeachydude** [drneavin/Demultiplexing_Doublet_Detecting_Docs#30]
Opening a separate issue for this. When I ran the full dropulation workflow the first time I ran into a peculiar error during the `dropulation_call.R` part. Executing the script via the singularity image à la `singularity exec /cluster/project/moor/resources/software/Demuxafy.sif dropulation_call.R ` resulted in the error below. 

```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

This appears to be an issue of the singularity image? I was able to get the script from your github and was able to run that just fine.

**Comment by drneavin** [comment]
I get that message every time I run it as well but it doesn't cause an issue for running. I've looked into how to remove/resolve this message but couldn't find a good solution and since it doesn't seem to impact running, I didn't want to dump too much time into the message. Did you by chance have other error messages that could have been the cause of the issues with running?
