### ISSUE TITLE
FATAL:   "Assign_Indiv_by_Geno.R": executable file not found in $PATH

### ISSUE THREAD

**Issue by MrLocuace** [drneavin/Demultiplexing_Doublet_Detecting_Docs#32]
Hello drneavin,
I am trying to run Assign_Indiv_by_Geno.R. 

module load apptainer/1.1.4

cd /project/X/USERS/Y/czi/data/scrna/fastqs

apptainer exec --bind /project/X/USERS/Y/czi/data/scrna/fastqs souporcell_latest.sif Assign_Indiv_by_Geno.R -r /project/X/USERS/Y/czi/data/scrna/fastqs/skip_remap_OUTS/LB-CC-20s-01-NI-GEX-b1-FC02_souporcell/batch1.MAF0.05.vcf.gz -c /project/X/USERS/Y/czi/data/scrna/fastqs/skip_remap_OUTS/LB-CC-20s-01-NI-GEX-b1-FC02_souporcell/cluster_genotypes.vcf -o /project/X/USERS/Y/czi/data/scrna/fastqs/skip_remap_OUTS/LB-CC-20s-01-NI-GEX-b1-FC02_souporcell

However, I get:

FATAL:   "Assign_Indiv_by_Geno.R": executable file not found in $PATH

I successfully ran souporcell and souporcell_summary.sh using apptainer instead of singularity, so the problem is not apptainer. For example, for the script souporcell_summary.sh, I do:

module load apptainer/1.1.4

cd /project/X/USERS/Y/czi/data/scrna/fastqs

apptainer exec --bind /project/X/USERS/Y/czi/data/scrna/fastqs souporcell_latest.sif bash souporcell_summary.sh /project/X/USERS/Y/czi/data/scrna/fastqs/skip_remap_OUTS/LB-CC-20s-01-NI-GEX-b1-FC02_souporcell/clusters.tsv > /project/X/USERS/Y/czi/data/scrna/fastqs/skip_remap_OUTS/LB-CC-20s-01-NI-GEX-b1-FC02_souporcell/souporcell_summary.tsv

Also, Assign_Indiv_by_Geno.R is in the same dir as souporcell_latest.sif, upstream of the othe input files, so that shouldn't be a problem.

Please help
Thank you !

**Comment by drneavin** [comment]
Hi @MrLocuace, it looks like you're using the souporcell singularity image, not the Demuxafy singularity image. For the provided command to work, you would need to use the Demuxafy.sif image since the script is in the image in a path already added to `$PATH` in the image. If you want to download it and run it using your own R environment, you would need to use `Rscript` to run the script which would mean you need R installed in your environment with all the required packages or you would need to activate a conda environment with R and all the required packages installed. The command would look like this

```
Rscript Assign_Indiv_by_Geno.R \
-r /project/X/USERS/Y/czi/data/scrna/fastqs/skip_remap_OUTS/LB-CC-20s-01-NI-GEX-b1-FC02_souporcell/batch1.MAF0.05.vcf.gz \
-c /project/X/USERS/Y/czi/data/scrna/fastqs/skip_remap_OUTS/LB-CC-20s-01-NI-GEX-b1-FC02_souporcell/cluster_genotypes.vcf \
-o /project/X/USERS/Y/czi/data/scrna/fastqs/skip_remap_OUTS/LB-CC-20s-01-NI-GEX-b1-FC02_souporcell
```

Let me know if you have any remaining questions!

**Comment by MrLocuace** [comment]
Thank you @drneavin. Yes, you are right. However, I am not able to download Demuxafy.sif. I posted a new Issue for that.

**Comment by drneavin** [comment]
Thanks @MrLocuace, I'll answer that question in the other issue. Cheers!
