### ISSUE TITLE
Error: package or namespace load failed for 'tidyverse' Combine_Results.R

### ISSUE THREAD

**Issue by dvbrown** [drneavin/Demultiplexing_Doublet_Detecting_Docs#6]
Dear Dr. Neavin,

I successfully ran multiple doublet detecting wrapper scripts through the singularity image. I am having trouble combining the results together with the Combine_Results.R script. I consistently have the error

Error: package or namespace load failed for 'tidyverse' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/stornext/HPCScratch/home/brown.d/R/x86_64-pc-linux-gnu-library/4.1/dplyr/libs/dplyr.so':
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /stornext/HPCScratch/home/brown.d/R/x86_64-pc-linux-gnu-library/4.1/dplyr/libs/dplyr.so)

Even the help command triggers this error

```
singularity exec Demuxafy.sif Combine_Results.R -h
```

My understanding is the singularity image contains all the dependancies including tidyverse. Can you offer some assistance please? I am running Image_version: = 1.0.3

**Comment by drneavin** [comment]
Hello! Thanks for reaching out.

I'm pretty sure that this is happening because your system is trying to load packages from your local location, not from the singularity image. For past scripts, I have hardcoded in the library location but it looks like I overlooked that with this script. I'll be sure to update that and release the new version soon but I don't have access to the computer that I use to build singularity images for a couple of weeks (so can't update it till then)

In the meantime, could you try setting R_LIBS_USER to "/usr/local/lib/R/site-library" before running the singularity command? And if that doesn't work, try setting R_LIBS_SITE to the same path as well. I'm hoping that will force it to pull from within the singularity image.

You might also try running 
``` 
singularity exec Deumuxafy.sif which R
```

To make sure that it's calling R from the image as opposed to on in your $PATH

Please let me know if any of those options work in the short term.

-Drew

**Comment by dvbrown** [comment]
Hi Drew,

Thanks changing both variables solved the issue. Please hardcode the path in the next version.
